import { PrismaClient } from '@prisma/client'
import * as dotenv from 'dotenv'
import * as path from 'path'

// Load environment variables from .env file
dotenv.config({ path: path.resolve(__dirname, '../.env') })

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting comprehensive African farm products seeding...')

  // Clean existing farm products data
  console.log('🗑️  Cleaning existing farm products data...')
  await prisma.farmProductReview.deleteMany()
  await prisma.farmOrderItem.deleteMany()
  await prisma.farmOrderStatusHistory.deleteMany()
  await prisma.farmOrder.deleteMany()
  await prisma.farmCartItem.deleteMany()
  await prisma.farmCart.deleteMany()
  await prisma.farmProduct.deleteMany()

  console.log('🥬 Creating comprehensive African farm products...')

  const products = [
    // ============ FRESH VEGETABLES ============
    {
      sku: 'FP-VEG-TOM-001',
      slug: 'fresh-tomatoes',
      name: 'Fresh Tomatoes',
      description: 'Juicy ripe tomatoes, locally sourced from African farms. Perfect for cooking, salads, and sauces.',
      category: 'FRESH_VEGETABLES',
      priceType: 'BOTH',
      retailPrice: 1500,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      bulkPrice: 28000,
      bulkUnit: 'basket',
      bulkQtyPerUnit: 20,
      bulkMinOrder: 1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 30,
      farmSource: 'West African Farms',
      isOrganic: false,
      isCertified: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['tomatoes.jpg'],
    },
    {
      sku: 'FP-VEG-CUC-002',
      slug: 'fresh-cucumber',
      name: 'Fresh Cucumber',
      description: 'Crisp and refreshing cucumbers, perfect for salads and garnishing.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1200,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Cameroon Vegetable Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['cucumber.jpg'],
    },
    {
      sku: 'FP-VEG-PEP-003',
      slug: 'bell-peppers',
      name: 'Bell Peppers (Mixed Colors)',
      description: 'Colorful bell peppers - red, yellow, and green. Rich in vitamins and antioxidants.',
      category: 'FRESH_VEGETABLES',
      priceType: 'BOTH',
      retailPrice: 2500,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      bulkPrice: 22000,
      bulkUnit: 'crate',
      bulkQtyPerUnit: 10,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'Nigerian Greenhouse Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['bell-peppers.jpg'],
    },
    {
      sku: 'FP-VEG-CAB-004',
      slug: 'green-cabbage',
      name: 'Green Cabbage',
      description: 'Fresh green cabbage heads, perfect for coleslaw, stir-fries, and traditional dishes.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 800,
      retailUnit: 'kg',
      retailMinQty: 1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 25,
      farmSource: 'Ethiopian Highland Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['cabbage.jpg'],
    },
    {
      sku: 'FP-VEG-CAR-005',
      slug: 'fresh-carrots',
      name: 'Fresh Carrots',
      description: 'Sweet, crunchy carrots. High in beta-carotene and vitamins. Great for salads and cooking.',
      category: 'FRESH_VEGETABLES',
      priceType: 'BOTH',
      retailPrice: 1400,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 12000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 10,
      bulkMinOrder: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 40,
      farmSource: 'Kenyan Vegetable Cooperative',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['carrots.jpg'],
    },
    {
      sku: 'FP-VEG-BEE-006',
      slug: 'fresh-beetroot',
      name: 'Fresh Beetroot',
      description: 'Deep red beetroot, rich in nutrients and natural sweetness. Perfect for salads and juices.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1800,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'South African Organic Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['beetroot.jpg'],
    },
    {
      sku: 'FP-VEG-ONI-007',
      slug: 'red-onions',
      name: 'Red Onions',
      description: 'Fresh red onions, sweet and flavorful. Essential for African cooking.',
      category: 'FRESH_VEGETABLES',
      priceType: 'BOTH',
      retailPrice: 2000,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 18000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 10,
      bulkMinOrder: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 30,
      farmSource: 'Niger Onion Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['red-onions.jpg'],
    },
    {
      sku: 'FP-VEG-OKR-008',
      slug: 'fresh-okra',
      name: 'Fresh Okra (Lady Fingers)',
      description: 'Fresh okra pods, perfect for soups, stews, and traditional African dishes.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1600,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Ghana Vegetable Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['okra.jpg'],
    },
    {
      sku: 'FP-VEG-EGG-009',
      slug: 'african-eggplant',
      name: 'African Eggplant (Garden Eggs)',
      description: 'Traditional African eggplant varieties, perfect for local dishes and stews.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1400,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'Togolese Organic Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['african-eggplant.jpg'],
    },
    {
      sku: 'FP-VEG-GRB-010',
      slug: 'green-beans',
      name: 'Green Beans',
      description: 'Fresh green beans, crisp and tender. Rich in fiber and vitamins.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2200,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Ugandan Farm Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['green-beans.jpg'],
    },
    {
      sku: 'FP-VEG-PEA-011',
      slug: 'fresh-peas',
      name: 'Fresh Peas',
      description: 'Sweet fresh peas in pods. Perfect for cooking and salads.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2800,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'Rwandan Highlands Farm',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['peas.jpg'],
    },
    {
      sku: 'FP-VEG-PUM-012',
      slug: 'pumpkin',
      name: 'African Pumpkin',
      description: 'Fresh African pumpkin, perfect for soups, stews, and traditional dishes.',
      category: 'FRESH_VEGETABLES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 900,
      retailUnit: 'kg',
      retailMinQty: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 30,
      farmSource: 'Malawian Pumpkin Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['pumpkin.jpg'],
    },

    // ============ TUBERS ============
    {
      sku: 'FP-TUB-SWP-013',
      slug: 'sweet-potatoes',
      name: 'Sweet Potatoes',
      description: 'Fresh sweet potatoes, rich in vitamins and natural sweetness. A staple in African cuisine.',
      category: 'TUBERS',
      priceType: 'BOTH',
      retailPrice: 1100,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 20000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 50,
      farmSource: 'Ugandan Sweet Potato Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['sweet-potatoes.jpg'],
    },
    {
      sku: 'FP-TUB-CAS-014',
      slug: 'cassava',
      name: 'Fresh Cassava',
      description: 'Fresh cassava tubers, perfect for fufu, garri, or boiling. A staple food across Africa.',
      category: 'TUBERS',
      priceType: 'BOTH',
      retailPrice: 1000,
      retailUnit: 'kg',
      retailMinQty: 3,
      bulkPrice: 18000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 60,
      farmSource: 'Nigerian Cassava Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['cassava.jpg'],
    },
    {
      sku: 'FP-TUB-YAM-015',
      slug: 'white-yam',
      name: 'White Yam',
      description: 'Premium quality white yam, a beloved staple food rich in carbohydrates.',
      category: 'TUBERS',
      priceType: 'BOTH',
      retailPrice: 2200,
      retailUnit: 'kg',
      retailMinQty: 5,
      bulkPrice: 40000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 75,
      farmSource: 'Benin Yam Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['white-yam.jpg'],
    },
    {
      sku: 'FP-TUB-POT-016',
      slug: 'irish-potatoes',
      name: 'Irish Potatoes',
      description: 'Fresh Irish potatoes, versatile for frying, boiling, or mashing.',
      category: 'TUBERS',
      priceType: 'BOTH',
      retailPrice: 1300,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 24000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 50,
      farmSource: 'Kenyan Highland Potato Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['irish-potatoes.jpg'],
    },
    {
      sku: 'FP-TUB-COC-017',
      slug: 'cocoyam',
      name: 'Cocoyam (Taro)',
      description: 'Fresh cocoyam tubers, perfect for traditional African dishes and soups.',
      category: 'TUBERS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1500,
      retailUnit: 'kg',
      retailMinQty: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 40,
      farmSource: 'Cameroonian Cocoyam Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['cocoyam.jpg'],
    },

    // ============ FRUITS ============
    {
      sku: 'FP-FRU-BAN-018',
      slug: 'bananas',
      name: 'Fresh Bananas',
      description: 'Sweet and ripe bananas from African plantations. Rich in potassium and natural energy.',
      category: 'FRUITS',
      priceType: 'BOTH',
      retailPrice: 1100,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 20000,
      bulkUnit: 'bunch',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 40,
      farmSource: 'Ivorian Banana Plantation',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['bananas.jpg'],
    },
    {
      sku: 'FP-FRU-PLA-019',
      slug: 'plantains',
      name: 'Plantains',
      description: 'Fresh plantains, perfect for frying, boiling, or roasting. A staple in African cuisine.',
      category: 'FRUITS',
      priceType: 'BOTH',
      retailPrice: 1200,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 22000,
      bulkUnit: 'bunch',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 50,
      farmSource: 'Ghanaian Plantain Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['plantains.jpg'],
    },
    {
      sku: 'FP-FRU-PIN-020',
      slug: 'pineapples',
      name: 'Fresh Pineapples',
      description: 'Sweet and juicy African pineapples. Packed with vitamin C and natural enzymes.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1500,
      retailUnit: 'piece',
      retailMinQty: 1,
      stockQuantity: 0,
      stockUnit: 'piece',
      lowStockThreshold: 20,
      farmSource: 'Benin Pineapple Plantation',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['pineapple.jpg'],
    },
    {
      sku: 'FP-FRU-MAN-021',
      slug: 'mangoes',
      name: 'African Mangoes',
      description: 'Sweet and succulent African mangoes. Perfect for eating fresh or making juice.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2000,
      retailUnit: 'kg',
      retailMinQty: 1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 30,
      farmSource: 'Senegalese Mango Orchards',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['mangoes.jpg'],
    },
    {
      sku: 'FP-FRU-PAP-022',
      slug: 'papayas',
      name: 'Fresh Papayas',
      description: 'Ripe papayas, rich in digestive enzymes and vitamins. Great for breakfast.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1800,
      retailUnit: 'kg',
      retailMinQty: 1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 25,
      farmSource: 'Tanzanian Papaya Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['papayas.jpg'],
    },
    {
      sku: 'FP-FRU-ORA-023',
      slug: 'oranges',
      name: 'Fresh Oranges',
      description: 'Juicy African oranges, packed with vitamin C. Perfect for fresh juice.',
      category: 'FRUITS',
      priceType: 'BOTH',
      retailPrice: 1600,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 28000,
      bulkUnit: 'crate',
      bulkQtyPerUnit: 20,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 40,
      farmSource: 'South African Citrus Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['oranges.jpg'],
    },
    {
      sku: 'FP-FRU-AVO-024',
      slug: 'avocados',
      name: 'African Avocados',
      description: 'Creamy African avocados, perfect for guacamole or toast. Packed with healthy fats.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 3200,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Kenyan Avocado Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['avocados.jpg'],
    },
    {
      sku: 'FP-FRU-WAT-025',
      slug: 'watermelon',
      name: 'Fresh Watermelon',
      description: 'Sweet and refreshing African watermelon. Perfect for hot days.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 800,
      retailUnit: 'kg',
      retailMinQty: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 50,
      farmSource: 'Nigerian Melon Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['watermelon.jpg'],
    },
    {
      sku: 'FP-FRU-GUA-026',
      slug: 'guavas',
      name: 'Fresh Guavas',
      description: 'Aromatic African guavas, rich in vitamin C and dietary fiber.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1400,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Zimbabwean Fruit Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['guavas.jpg'],
    },
    {
      sku: 'FP-FRU-PAS-027',
      slug: 'passion-fruit',
      name: 'Passion Fruit',
      description: 'Tropical passion fruit, perfect for juices and desserts. Rich in antioxidants.',
      category: 'FRUITS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2500,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'Ugandan Passion Fruit Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['passion-fruit.jpg'],
    },

    // ============ GRAINS & CEREALS ============
    {
      sku: 'FP-GRA-MAI-028',
      slug: 'maize-corn',
      name: 'Yellow Maize (Corn)',
      description: 'Fresh yellow maize, perfect for grinding into flour or traditional dishes.',
      category: 'GRAINS_CEREALS',
      priceType: 'BOTH',
      retailPrice: 1600,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 28000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 100,
      farmSource: 'Zambian Maize Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['maize.jpg'],
    },
    {
      sku: 'FP-GRA-RIC-029',
      slug: 'african-rice',
      name: 'African Rice',
      description: 'Premium local African rice. Aromatic and nutritious.',
      category: 'GRAINS_CEREALS',
      priceType: 'BOTH',
      retailPrice: 2000,
      retailUnit: 'kg',
      retailMinQty: 5,
      bulkPrice: 42000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 150,
      farmSource: 'Senegalese Rice Mills',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['rice.jpg'],
    },
    {
      sku: 'FP-GRA-MIL-030',
      slug: 'pearl-millet',
      name: 'Pearl Millet',
      description: 'Nutritious pearl millet, drought-resistant African grain. Rich in minerals.',
      category: 'GRAINS_CEREALS',
      priceType: 'BOTH',
      retailPrice: 1800,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 32000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 80,
      farmSource: 'Niger Millet Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['millet.jpg'],
    },
    {
      sku: 'FP-GRA-SOR-031',
      slug: 'sorghum',
      name: 'Sorghum',
      description: 'Traditional African sorghum grain, gluten-free and highly nutritious.',
      category: 'GRAINS_CEREALS',
      priceType: 'BOTH',
      retailPrice: 1700,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 30000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 90,
      farmSource: 'Sudanese Sorghum Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['sorghum.jpg'],
    },

    // ============ LEGUMES ============
    {
      sku: 'FP-LEG-COW-032',
      slug: 'cowpeas',
      name: 'Cowpeas (Black-eyed Peas)',
      description: 'Protein-rich cowpeas, a staple legume across Africa. Perfect for stews and soups.',
      category: 'LEGUMES',
      priceType: 'BOTH',
      retailPrice: 2400,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 22000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 10,
      bulkMinOrder: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 60,
      farmSource: 'Nigerian Cowpea Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['cowpeas.jpg'],
    },
    {
      sku: 'FP-LEG-GRO-033',
      slug: 'groundnuts',
      name: 'Groundnuts (Peanuts)',
      description: 'Fresh groundnuts, rich in protein and healthy oils. Great for snacking and cooking.',
      category: 'LEGUMES',
      priceType: 'BOTH',
      retailPrice: 2800,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 25000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 10,
      bulkMinOrder: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 70,
      farmSource: 'Gambian Groundnut Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['groundnuts.jpg'],
    },
    {
      sku: 'FP-LEG-SOY-034',
      slug: 'soybeans',
      name: 'Soybeans',
      description: 'High-protein soybeans, versatile for making milk, tofu, and traditional dishes.',
      category: 'LEGUMES',
      priceType: 'BOTH',
      retailPrice: 2600,
      retailUnit: 'kg',
      retailMinQty: 2,
      bulkPrice: 48000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 25,
      bulkMinOrder: 2,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 100,
      farmSource: 'Zimbabwean Soybean Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['soybeans.jpg'],
    },
    {
      sku: 'FP-LEG-CHI-035',
      slug: 'chickpeas',
      name: 'Chickpeas',
      description: 'Nutritious chickpeas, perfect for hummus, stews, and salads.',
      category: 'LEGUMES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 3000,
      retailUnit: 'kg',
      retailMinQty: 1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 50,
      farmSource: 'Ethiopian Chickpea Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['chickpeas.jpg'],
    },
    {
      sku: 'FP-LEG-LEN-036',
      slug: 'red-lentils',
      name: 'Red Lentils',
      description: 'Quick-cooking red lentils, rich in protein and iron. Perfect for soups and dals.',
      category: 'LEGUMES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2900,
      retailUnit: 'kg',
      retailMinQty: 1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 40,
      farmSource: 'Ethiopian Lentil Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['lentils.jpg'],
    },
    {
      sku: 'FP-LEG-KID-037',
      slug: 'kidney-beans',
      name: 'Red Kidney Beans',
      description: 'High-protein kidney beans, perfect for stews, salads, and rice dishes.',
      category: 'LEGUMES',
      priceType: 'BOTH',
      retailPrice: 2700,
      retailUnit: 'kg',
      retailMinQty: 1,
      bulkPrice: 24000,
      bulkUnit: 'bag',
      bulkQtyPerUnit: 10,
      bulkMinOrder: 3,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 50,
      farmSource: 'Kenyan Bean Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['kidney-beans.jpg'],
    },

    // ============ LEAFY GREENS ============
    {
      sku: 'FP-LEA-SPI-038',
      slug: 'african-spinach',
      name: 'African Spinach',
      description: 'Fresh African spinach, rich in iron and vitamins. Perfect for traditional dishes.',
      category: 'LEAFY_GREENS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2200,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Tanzanian Leafy Vegetable Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['african-spinach.jpg'],
    },
    {
      sku: 'FP-LEA-KAL-039',
      slug: 'kale',
      name: 'Fresh Kale',
      description: 'Nutritious kale, superfood packed with vitamins and antioxidants.',
      category: 'LEAFY_GREENS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2500,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'Kenyan Organic Vegetable Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['kale.jpg'],
    },
    {
      sku: 'FP-LEA-AMA-040',
      slug: 'amaranth-leaves',
      name: 'Amaranth Leaves',
      description: 'Traditional African amaranth leaves, rich in nutrients. Perfect for soups and stews.',
      category: 'LEAFY_GREENS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1800,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'West African Vegetable Cooperative',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['amaranth.jpg'],
    },
    {
      sku: 'FP-LEA-BIT-041',
      slug: 'bitter-leaf',
      name: 'Bitter Leaf (Vernonia)',
      description: 'Traditional African bitter leaf, known for its medicinal properties and unique flavor.',
      category: 'LEAFY_GREENS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2000,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'Cameroonian Traditional Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['bitter-leaf.jpg'],
    },
    {
      sku: 'FP-LEA-HUC-042',
      slug: 'huckleberry-leaves',
      name: 'African Huckleberry Leaves',
      description: 'Nutritious African huckleberry leaves, perfect for traditional vegetable dishes.',
      category: 'LEAFY_GREENS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1600,
      retailUnit: 'kg',
      retailMinQty: 0.5,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 20,
      farmSource: 'Ugandan Leafy Greens Farm',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['huckleberry.jpg'],
    },
    {
      sku: 'FP-LEA-LET-043',
      slug: 'lettuce',
      name: 'Fresh Lettuce',
      description: 'Crisp and fresh lettuce, perfect for salads and sandwiches.',
      category: 'LEAFY_GREENS',
      priceType: 'RETAIL_ONLY',
      retailPrice: 1700,
      retailUnit: 'kg',
      retailMinQty: 0.25,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 15,
      farmSource: 'South African Lettuce Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['lettuce.jpg'],
    },

    // ============ HERBS & SPICES ============
    {
      sku: 'FP-HER-GIN-044',
      slug: 'fresh-ginger',
      name: 'Fresh Ginger',
      description: 'Aromatic fresh ginger root, perfect for teas, cooking, and natural remedies.',
      category: 'HERBS_SPICES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 4200,
      retailUnit: 'kg',
      retailMinQty: 0.25,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 10,
      farmSource: 'Nigerian Spice Farms',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['ginger.jpg'],
    },
    {
      sku: 'FP-HER-GAR-045',
      slug: 'garlic',
      name: 'Fresh Garlic',
      description: 'Aromatic fresh garlic bulbs. Essential for African cooking and natural medicine.',
      category: 'HERBS_SPICES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 5500,
      retailUnit: 'kg',
      retailMinQty: 0.25,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 10,
      farmSource: 'Ethiopian Garlic Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['garlic.jpg'],
    },
    {
      sku: 'FP-HER-CHI-046',
      slug: 'scotch-bonnet-peppers',
      name: 'Scotch Bonnet Peppers',
      description: 'Fiery hot Scotch bonnet peppers, essential for authentic African cuisine.',
      category: 'HERBS_SPICES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 3500,
      retailUnit: 'kg',
      retailMinQty: 0.1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 5,
      farmSource: 'Jamaican/West African Pepper Farms',
      isOrganic: false,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['scotch-bonnet.jpg'],
    },
    {
      sku: 'FP-HER-SCE-047',
      slug: 'scent-leaf',
      name: 'Scent Leaf (Basil)',
      description: 'African scent leaf (basil), aromatic herb perfect for soups and sauces.',
      category: 'HERBS_SPICES',
      priceType: 'RETAIL_ONLY',
      retailPrice: 2000,
      retailUnit: 'kg',
      retailMinQty: 0.1,
      stockQuantity: 0,
      stockUnit: 'kg',
      lowStockThreshold: 5,
      farmSource: 'Nigerian Herb Gardens',
      isOrganic: true,
      status: 'OUT_OF_STOCK',
      isAvailable: false,
      images: ['scent-leaf.jpg'],
    },
  ]

  console.log(`📦 Creating ${products.length} products...`)

  for (const product of products) {
    await prisma.farmProduct.create({
      data: product,
    })
  }

  console.log('✅ African farm products seeding completed successfully!')
  console.log('')
  console.log('📊 Summary:')
  console.log(`  - Total products: ${products.length}`)
  console.log('  - Fresh Vegetables: 12 products')
  console.log('  - Tubers: 5 products')
  console.log('  - Fruits: 10 products')
  console.log('  - Grains & Cereals: 4 products')
  console.log('  - Legumes: 6 products')
  console.log('  - Leafy Greens: 6 products')
  console.log('  - Herbs & Spices: 4 products')
  console.log('')
  console.log('  - ALL products are OUT_OF_STOCK (stockQuantity: 0)')
  console.log('  - Organic certified: 9 products')
  console.log('')
  console.log('💰 All prices are in XAF (FCFA - Central African Franc)')
  console.log('🌍 All products sourced from various African countries')
  console.log('🖼️  Product images need to be uploaded to the server')
  console.log('')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding African farm products:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
