'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  ArrowLeft,
  Plus,
  Minus,
  ShoppingCart,
  Clock,
  Users,
  Flame,
  AlertCircle,
  Check,
} from 'lucide-react';
import { useCartStore, useCartRestaurantCheck } from '@/store/cartStore';

interface Ingredient {
  ingredient: string;
  required: number;
  available: number;
  unit: string;
  sufficient: boolean;
}

interface MenuItem {
  id: string;
  name: string;
  description: string | null;
  price: number;
  salePrice: number | null;
  image: string | null;
  category: string;
  isVegetarian: boolean;
  isVegan: boolean;
  isGlutenFree: boolean;
  calories: number | null;
  preparationTime: number | null;
  spiceLevel: number | null;
  allergens: string[];
  ingredients: string | null;
  inventoryCheck: Ingredient[];
}

export default function MenuItemDetailPage() {
  const params = useParams();
  const router = useRouter();
  const [menuItem, setMenuItem] = useState<MenuItem | null>(null);
  const [restaurant, setRestaurant] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Cart state
  const [quantity, setQuantity] = useState(1);
  const [removedIngredients, setRemovedIngredients] = useState<string[]>([]);
  const [specialInstructions, setSpecialInstructions] = useState('');
  const addToCart = useCartStore((state) => state.addItem);
  const { hasDifferentRestaurant, cartRestaurantId } = useCartRestaurantCheck(
    params.id as string
  );

  useEffect(() => {
    fetchMenuItemAndRestaurant();
  }, [params.id, params.menuItemId]);

  const fetchMenuItemAndRestaurant = async () => {
    try {
      setLoading(true);

      // Fetch restaurant details
      const restaurantRes = await fetch(`/api/locations/${params.id}`);
      if (!restaurantRes.ok) throw new Error('Failed to fetch restaurant');
      const restaurantData = await restaurantRes.json();
      setRestaurant(restaurantData);

      // Fetch menu to find this specific item
      const menuRes = await fetch(`/api/locations/${params.id}/menu`);
      if (!menuRes.ok) throw new Error('Failed to fetch menu');
      const menuData = await menuRes.json();

      const item = menuData.allItems.find(
        (item: MenuItem) => item.id === params.menuItemId
      );

      if (!item) {
        throw new Error('Menu item not found');
      }

      setMenuItem(item);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  const toggleIngredient = (ingredient: string) => {
    setRemovedIngredients((prev) =>
      prev.includes(ingredient)
        ? prev.filter((i) => i !== ingredient)
        : [...prev, ingredient]
    );
  };

  const handleAddToCart = () => {
    if (!menuItem || !restaurant) return;

    // Check if adding from different restaurant
    if (hasDifferentRestaurant) {
      if (!confirm(
        `Your cart contains items from another restaurant. Do you want to clear it and add this item?`
      )) {
        return;
      }
      useCartStore.getState().clearCart();
    }

    const currentPrice = menuItem.salePrice || menuItem.price;

    addToCart({
      id: '', // Will be generated by store
      menuItemId: menuItem.id,
      name: menuItem.name,
      price: currentPrice,
      quantity,
      image: menuItem.image,
      restaurantId: params.id as string,
      restaurantName: restaurant.name,
      category: menuItem.category,
      preparationTime: menuItem.preparationTime,
      customization:
        removedIngredients.length > 0 || specialInstructions
          ? {
              removedIngredients,
              specialInstructions: specialInstructions || undefined,
            }
          : undefined,
    });

    // Show success message
    alert(`Added ${quantity} ${menuItem.name} to cart!`);

    // Reset customization
    setQuantity(1);
    setRemovedIngredients([]);
    setSpecialInstructions('');
  };

  const getDietaryBadges = () => {
    if (!menuItem) return [];
    const badges = [];
    if (menuItem.isVegan) badges.push({ label: 'Vegan', color: 'bg-green-100 text-green-800' });
    else if (menuItem.isVegetarian)
      badges.push({ label: 'Vegetarian', color: 'bg-green-100 text-green-800' });
    if (menuItem.isGlutenFree)
      badges.push({ label: 'Gluten-Free', color: 'bg-blue-100 text-blue-800' });
    return badges;
  };

  const getIngredientsList = (): string[] => {
    if (!menuItem?.inventoryCheck) return [];
    return menuItem.inventoryCheck.map((item) => item.ingredient);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading menu item...</p>
        </div>
      </div>
    );
  }

  if (error || !menuItem) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600">Error: {error || 'Menu item not found'}</p>
          <button
            onClick={() => router.push(`/locations/${params.id}/menu`)}
            className="mt-4 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
          >
            Back to Menu
          </button>
        </div>
      </div>
    );
  }

  const currentPrice = menuItem.salePrice || menuItem.price;
  const totalPrice = currentPrice * quantity;
  const ingredientsList = getIngredientsList();

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <button
            onClick={() => router.push(`/locations/${params.id}/menu`)}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft size={20} />
            Back to Menu
          </button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          {/* Image */}
          <div className="h-64 md:h-96 bg-gray-200 relative">
            {menuItem.image ? (
              <img
                src={menuItem.image}
                alt={menuItem.name}
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-gray-400">
                <ShoppingCart size={96} />
              </div>
            )}
          </div>

          <div className="p-6">
            {/* Title & Price */}
            <div className="flex items-start justify-between mb-4">
              <div className="flex-1">
                <h1 className="text-3xl font-bold text-gray-900 mb-2">{menuItem.name}</h1>
                <p className="text-gray-600 mb-3">{menuItem.description}</p>

                {/* Badges */}
                <div className="flex flex-wrap gap-2">
                  {getDietaryBadges().map((badge, idx) => (
                    <span key={idx} className={`px-3 py-1 text-sm rounded-full ${badge.color}`}>
                      {badge.label}
                    </span>
                  ))}
                </div>
              </div>

              <div className="text-right ml-4">
                {menuItem.salePrice ? (
                  <>
                    <p className="text-3xl font-bold text-green-600">
                      {menuItem.salePrice.toLocaleString('fr-FR')} XAF
                    </p>
                    <p className="text-lg text-gray-500 line-through">
                      {menuItem.price.toLocaleString('fr-FR')} XAF
                    </p>
                  </>
                ) : (
                  <p className="text-3xl font-bold text-gray-900">
                    {menuItem.price.toLocaleString('fr-FR')} XAF
                  </p>
                )}
              </div>
            </div>

            {/* Meta Info */}
            <div className="flex flex-wrap gap-4 py-4 border-y text-sm text-gray-600">
              {menuItem.preparationTime && (
                <div className="flex items-center gap-2">
                  <Clock size={18} />
                  <span>{menuItem.preparationTime} min</span>
                </div>
              )}
              {menuItem.calories && (
                <div className="flex items-center gap-2">
                  <Flame size={18} />
                  <span>{menuItem.calories} cal</span>
                </div>
              )}
              {menuItem.spiceLevel && (
                <div className="flex items-center gap-2">
                  <span>🌶️</span>
                  <span>Spice: {menuItem.spiceLevel}/5</span>
                </div>
              )}
            </div>

            {/* Allergens */}
            {menuItem.allergens && menuItem.allergens.length > 0 && (
              <div className="mt-4 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
                <div className="flex items-start gap-2">
                  <AlertCircle size={20} className="text-yellow-600 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="font-medium text-yellow-900">Allergen Information</p>
                    <p className="text-sm text-yellow-800">
                      Contains: {menuItem.allergens.join(', ')}
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* Ingredients Customization */}
            {ingredientsList.length > 0 && (
              <div className="mt-6">
                <h2 className="text-xl font-semibold mb-3">Customize Your Order</h2>
                <p className="text-sm text-gray-600 mb-3">
                  Select ingredients you'd like to remove:
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {ingredientsList.map((ingredient) => {
                    const isRemoved = removedIngredients.includes(ingredient);
                    return (
                      <button
                        key={ingredient}
                        onClick={() => toggleIngredient(ingredient)}
                        className={`flex items-center gap-3 p-3 border rounded-lg transition ${
                          isRemoved
                            ? 'bg-red-50 border-red-300 text-red-900'
                            : 'bg-white border-gray-200 hover:border-blue-300'
                        }`}
                      >
                        <div
                          className={`w-5 h-5 border-2 rounded flex items-center justify-center ${
                            isRemoved
                              ? 'bg-red-500 border-red-500'
                              : 'border-gray-300'
                          }`}
                        >
                          {isRemoved && <Check size={16} className="text-white" />}
                        </div>
                        <span className="capitalize">{ingredient}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Special Instructions */}
            <div className="mt-6">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Special Instructions (Optional)
              </label>
              <textarea
                value={specialInstructions}
                onChange={(e) => setSpecialInstructions(e.target.value)}
                placeholder="Any special requests? (e.g., extra sauce, cook well done, etc.)"
                rows={3}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            {/* Quantity & Add to Cart */}
            <div className="mt-6 flex items-center gap-4">
              {/* Quantity Controls */}
              <div className="flex items-center gap-3 border border-gray-300 rounded-lg p-2">
                <button
                  onClick={() => setQuantity(Math.max(1, quantity - 1))}
                  className="p-2 hover:bg-gray-100 rounded transition"
                  disabled={quantity <= 1}
                >
                  <Minus size={20} />
                </button>
                <span className="w-12 text-center font-semibold text-lg">{quantity}</span>
                <button
                  onClick={() => setQuantity(quantity + 1)}
                  className="p-2 hover:bg-gray-100 rounded transition"
                >
                  <Plus size={20} />
                </button>
              </div>

              {/* Add to Cart Button */}
              <button
                onClick={handleAddToCart}
                className="flex-1 bg-blue-600 text-white py-4 rounded-lg font-semibold hover:bg-blue-700 transition flex items-center justify-center gap-3"
              >
                <ShoppingCart size={20} />
                Add to Cart • {totalPrice.toLocaleString('fr-FR')} XAF
              </button>
            </div>

            {/* Different Restaurant Warning */}
            {hasDifferentRestaurant && (
              <div className="mt-4 p-3 bg-orange-50 border border-orange-200 rounded-lg">
                <p className="text-sm text-orange-800">
                  <strong>Note:</strong> Your cart contains items from another restaurant.
                  Adding this item will clear your current cart.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
